version: "3.3"
services:
  mysqldb:
    container_name: mysqldb1
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306 
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: wassimbelgacem/wassimbelgacem_5ds2-achat
    container_name: devopscontainer
    restart: on-failure
    ports:
      - 8089:8089
    depends_on:
      - mysqldb  
